name: Upload website to S3 and invalidate CloudFront cache

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master

            - name: Terraform Init
              uses: hashicorp/terraform-github-actions/init@v0.4.0

            - name: Terraform Validate
              uses: hashicorp/terraform-github-actions/validate@v0.3.7

            - name: Terraform Apply
              uses: hashicorp/terraform-github-actions/apply@v0.4.0

            - name: Sync S3
              uses: jakejarvis/s3-sync-action@master

            - name: Invalidate CloudFront cache
              uses: chetan/invalidate-cloudfront-action@v2
        env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_REGION: 'us-east-2'
            TF_ACTION_WORKING_DIR: 'infra'
            PATHS: "/"